const KEY='englishMaster_v1', DATA_URL='https://exist8506-bot.github.io/english-master-data/data/version.json';
let db={vocab:[],sentences:[],questions:[],grammar:[],communication:[],trilingual:[],stats:{xp:0,streak:0,learned:0,answered:0,correct:0},profile:{theme:'light',autoUpdate:true},lastRemoteVersion:null};
let view='home', flashIndex=0, flashFlipped=false, speakIndex=0, listenIndex=0, quizIndex=0, quizAnswered=false;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s??'').trim().toLowerCase().replace(/\s+/g,' ');
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function toast(s){const e=$('toast');e.textContent=s;e.className='show';setTimeout(()=>e.className='',2500)}
function speak(t,rate=1){if(!('speechSynthesis'in window)){toast('Trình duyệt không hỗ trợ đọc giọng nói');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(t));u.lang='en-US';u.rate=rate;speechSynthesis.speak(u)}
function merge(oldArr,newArr,key){const out=Array.isArray(oldArr)?[...oldArr]:[],seen=new Set(out.map(key).filter(Boolean));for(const x of newArr||[]){const k=key(x);if(k&&!seen.has(k)){out.push(x);seen.add(k)}}return out}
async function getJSON(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
const sibling=f=>DATA_URL.replace(/\/[^/]+$/,'/'+f);
async function updateOnline(force=false){try{const m=await getJSON(DATA_URL),ver=String(m.version??'');if(!ver)return;if(!force&&db.lastRemoteVersion===ver)return;const files=m.files||{},names={vocab:files.vocabulary||'vocabulary.json',sentences:files.sentences||'sentences.json',questions:files.questions||'questions.json',grammar:files.grammar||'grammar.json',communication:files.communication||'communication.json',trilingual:files.trilingual||'trilingual.json'};let added=0;for(const [key,file] of Object.entries(names)){try{const d=await getJSON(/^https?:/i.test(file)?file:sibling(file)),arr=Array.isArray(d)?d:(Array.isArray(d[key])?d[key]:[]),before=db[key].length;db[key]=merge(db[key],arr,x=>x.id||norm(x.word||x.en||x.title||x.prompt));added+=db[key].length-before}catch(e){if(key==='vocab')throw e}}db.lastRemoteVersion=ver;save();render();toast(added?'Đã cập nhật '+added+' mục từ GitHub':'Đã kiểm tra: không có dữ liệu mới')}catch(e){if(force)toast('Cập nhật lỗi: '+e.message)}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)db={...db,...x,stats:{...db.stats,...x.stats},profile:{...db.profile,...x.profile}}}catch{}}
function show(v){view=v;render()}
function shell(t,s=''){return '<div class="card hero"><h1 class="title">'+t+'</h1><p class="muted">'+s+'</p></div>'}
function render(){document.querySelectorAll('aside button').forEach(b=>b.classList.remove('active'));$('streak').textContent=db.stats.streak||0;({home,vocab,sentences,flashcards,quiz,listening,speaking,grammar,communication,trilingual,review,stats,settings}[view]||home)();document.body.classList.toggle('dark',db.profile.theme==='dark')}
function home(){$('view').innerHTML=shell('English Master V4','Học – Luyện – Nhớ – Cải thiện')+'<div class="grid"><div class="card"><div class="big">'+db.vocab.length+'</div><div class="muted">Từ vựng</div></div><div class="card"><div class="big">'+db.sentences.length+'</div><div class="muted">Câu học tập</div></div><div class="card"><div class="big">'+db.questions.length+'</div><div class="muted">Câu trắc nghiệm</div></div></div><div class="card"><h2>Học nhanh</h2><div class="actions"><button class="primary" onclick="show(\'flashcards\')">🃏 Flashcards</button><button onclick="show(\'speaking\')">🎙️ Phát âm</button><button onclick="show(\'listening\')">🎧 Luyện nghe</button><button onclick="show(\'quiz\')">🧠 Trắc nghiệm</button></div></div>'}
function vocab(){const a=db.vocab.slice(0,200);$('view').innerHTML=shell('Học từ vựng','500+ từ có IPA, nghĩa và ví dụ.')+'<div class="card"><input id="vs" placeholder="Tìm từ..." oninput="filterV()"></div><div id="vlist" class="list">'+a.map(v=>'<div class="item"><div class="row"><div style="flex:1"><b class="word">'+esc(v.word)+'</b> <span class="ipa">'+esc(v.ipa||'')+'</span><p>'+esc(v.meaning)+'</p><span class="muted small">'+esc(v.example||'')+'</span></div><button onclick="speak(\''+String(v.word).replace(/'/g,"\\'")+'\')">🔊</button></div></div>').join('')+'</div>'}
function filterV(){const q=norm($('vs').value),a=db.vocab.filter(v=>norm(v.word).includes(q)||norm(v.meaning).includes(q)).slice(0,200);$('vlist').innerHTML=a.map(v=>'<div class="item"><b class="word">'+esc(v.word)+'</b> <span class="ipa">'+esc(v.ipa||'')+'</span><p>'+esc(v.meaning)+'</p><button onclick="speak(\''+String(v.word).replace(/'/g,"\\'")+'\')">🔊 Nghe</button></div>').join('')}
function sentences(){$('view').innerHTML=shell('Học câu','Câu mẫu được lấy trực tiếp từ bộ dữ liệu online.')+'<div class="list">'+db.sentences.slice(0,200).map(s=>'<div class="item"><b>'+esc(s.en)+'</b><p class="muted">'+esc(s.vi)+'</p><span class="badge">'+esc(s.topic||'daily')+'</span> <button onclick="speak(\''+String(s.en).replace(/'/g,"\\'")+'\')">🔊</button></div>').join('')+'</div>'}
function flashcards(){if(!db.vocab.length){$('view').innerHTML=shell('Flashcards','Chưa có từ vựng.');return}const v=db.vocab[flashIndex%db.vocab.length];$('view').innerHTML=shell('Flashcards','Bấm vào thẻ để lật. Sau đó tự đánh giá mức nhớ.')+'<div class="card flash" onclick="flashFlipped=!flashFlipped;flashcards()">'+(flashFlipped?'<div><div class="big">'+esc(v.meaning)+'</div><p>'+esc(v.example||'')+'</p><p class="muted">'+esc(v.exampleVi||'')+'</p><button onclick="event.stopPropagation();speak(\''+String(v.word).replace(/'/g,"\\'")+'\')">🔊 Nghe từ</button></div>':'<div><div class="big">'+esc(v.word)+'</div><div class="ipa">'+esc(v.ipa||'')+'</div><p class="muted">Bấm để lật thẻ</p></div>')+'</div><div class="actions"><button onclick="rate(0)">😵 Chưa nhớ</button><button onclick="rate(1)">🙂 Đã nhớ</button><button onclick="rate(2)">😎 Rất dễ</button><button onclick="shuffle()">🔀 Ngẫu nhiên</button></div><p class="muted">Thẻ '+(flashIndex%db.vocab.length+1)+' / '+db.vocab.length+'</p>'}
function rate(){db.stats.learned++;db.stats.xp+=5;flashIndex=(flashIndex+1)%db.vocab.length;flashFlipped=false;save();render()}function shuffle(){flashIndex=Math.floor(Math.random()*db.vocab.length);flashFlipped=false;render()}
function speaking(){if(!db.sentences.length){$('view').innerHTML=shell('Phát âm','Chưa có câu luyện nói.');return}const s=db.sentences[speakIndex%db.sentences.length],v=db.vocab.find(x=>norm(x.word)===norm(s.vocabWord));$('view').innerHTML=shell('Luyện phát âm','Luyện theo từng câu; trình duyệt sẽ nhận diện giọng nói nếu hỗ trợ.')+'<div class="card"><span class="badge">'+esc(s.topic||'daily')+'</span><h2>'+esc(s.en)+'</h2><p class="muted">'+esc(s.vi)+'</p><div class="hint"><b>Từ trọng tâm:</b> '+esc(s.vocabWord||'')+' <span class="ipa">'+esc(v?.ipa||'')+'</span></div><div class="actions" style="margin-top:15px"><button class="primary" onclick="speak(\''+String(s.en).replace(/'/g,"\\'")+'\')">🔊 Nghe mẫu</button><button onclick="speak(\''+String(s.vocabWord||'').replace(/'/g,"\\'")+'\')">🔊 Nghe từ</button><button onclick="recognize()">🎙️ Bắt đầu nói</button><button onclick="prevSpeak()">← Trước</button><button onclick="nextSpeak()">Tiếp →</button></div><div id="speech" class="hint" style="margin-top:15px">Hãy nghe mẫu rồi nói lại.</div></div><div class="grid"><div class="card"><div class="big">'+(speakIndex%db.sentences.length+1)+'</div><div class="muted">Câu luyện nói</div></div><div class="card"><div class="big">'+db.sentences.length+'</div><div class="muted">Tổng câu</div></div><div class="card"><div class="big">IPA</div><div class="muted">'+esc(v?.ipa||'')+'</div></div></div>'}
function nextSpeak(){speakIndex=(speakIndex+1)%db.sentences.length;render()}function prevSpeak(){speakIndex=(speakIndex-1+db.sentences.length)%db.sentences.length;render()}
function recognize(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('Trình duyệt chưa hỗ trợ nhận diện giọng nói');return}const target=db.sentences[speakIndex%db.sentences.length].en,r=new R();r.lang='en-US';r.interimResults=false;r.onresult=e=>{const got=e.results[0][0].transcript,a=norm(got).split(' '),b=norm(target).split(' '),same=a.filter(x=>b.includes(x)).length,score=Math.round(same/Math.max(a.length,b.length)*100);$('speech').innerHTML='<b>Bạn nói:</b> '+esc(got)+'<br><b>Mức khớp:</b> '+score+'%';if(score>=80){db.stats.xp+=10;save()}};r.onerror=()=>toast('Không nhận được giọng nói');r.start()}
function listening(){if(!db.sentences.length){$('view').innerHTML=shell('Luyện nghe','Chưa có câu.');return}const s=db.sentences[listenIndex%db.sentences.length],opts=[s.vi,...db.sentences.filter(x=>x.id!==s.id).slice(0,3).map(x=>x.vi)].filter(Boolean);$('view').innerHTML=shell('Luyện nghe','Nghe câu rồi chọn nghĩa tiếng Việt.')+'<div class="card"><h2>🔊 Nghe câu</h2><button class="primary" onclick="speak(\''+String(s.en).replace(/'/g,"\\'")+'\',0.75)">0.75×</button> <button onclick="speak(\''+String(s.en).replace(/'/g,"\\'")+'\')">1×</button> <button onclick="speak(\''+String(s.en).replace(/'/g,"\\'")+'\',1.25)">1.25×</button><div class="options" style="margin-top:18px">'+opts.map(o=>'<button class="option" onclick="listenAnswer(this,\''+String(o).replace(/'/g,"\\'")+'\',\''+String(s.vi).replace(/'/g,"\\'")+'\')">'+esc(o)+'</button>').join('')+'</div><div id="lres" class="hint" style="margin-top:15px">Chọn đáp án.</div></div>'}
function listenAnswer(el,o,c){document.querySelectorAll('.option').forEach(x=>x.disabled=true);const ok=norm(o)===norm(c);el.classList.add(ok?'correct':'wrong');$('lres').textContent=ok?'✓ Chính xác':'✗ Đáp án: '+c;db.stats.answered++;if(ok){db.stats.correct++;db.stats.xp+=10}listenIndex=(listenIndex+1)%db.sentences.length;save()}
function quiz(){if(!db.questions.length){$('view').innerHTML=shell('Trắc nghiệm','Chưa có câu hỏi.');return}const q=db.questions[quizIndex%db.questions.length];$('view').innerHTML=shell('Trắc nghiệm','Chọn một đáp án.')+'<div class="card"><span class="badge">'+esc(q.topic||'daily')+'</span><h2>'+esc(q.prompt)+'</h2><div class="options">'+(q.options||[]).map((o,i)=>'<button class="option" onclick="answerQuiz('+i+','+Number(q.answer)+')">'+esc(o)+'</button>').join('')+'</div><div id="qres" class="hint" style="margin-top:15px">Câu '+(quizIndex+1)+' / '+db.questions.length+'</div></div>'}
function answerQuiz(i,a){if(quizAnswered)return;quizAnswered=true;const ok=i===a;db.stats.answered++;if(ok){db.stats.correct++;db.stats.xp+=10}document.querySelectorAll('.option').forEach((b,j)=>{b.disabled=true;if(j===a)b.classList.add('correct');if(j===i&&!ok)b.classList.add('wrong')});$('qres').innerHTML=(ok?'✓ Chính xác':'✗ Chưa đúng')+' — <button onclick="nextQuiz()">Câu tiếp →</button>';save()}
function nextQuiz(){quizIndex=(quizIndex+1)%db.questions.length;quizAnswered=false;render()}
function grammar(){$('view').innerHTML=shell('Ngữ pháp','Các bài ngữ pháp được đồng bộ từ GitHub.')+'<div class="list">'+db.grammar.map(g=>'<div class="card"><h2>'+esc(g.title)+'</h2><span class="badge">'+esc(g.level||'Beginner')+'</span><p>'+esc(g.explain||'')+'</p><div class="hint">'+esc(g.formula||'')+'</div><h4>Ví dụ</h4>'+((g.examples||[]).map(x=>'<div>• '+esc(x)+'</div>').join(''))+'</div>').join('')+'</div>'}
function communication(){$('view').innerHTML=shell('Giao tiếp','Các chủ đề giao tiếp thực tế.')+'<div class="list">'+db.communication.map(c=>'<div class="card"><h2>'+esc(c.title)+'</h2>'+((c.lines||[]).map(x=>'<p><b>'+esc(x[0])+':</b> '+esc(x[1])+'</p>').join(''))+'</div>').join('')+'</div>'}
function trilingual(){$('view').innerHTML=shell('Tam ngữ','Anh – Trung – Việt.')+(db.trilingual.length?'<div class="list">'+db.trilingual.map(x=>'<div class="item"><b>'+esc(x.en)+'</b><p>'+esc(x.chinese||x.zh||'')+' '+esc(x.pinyin||'')+'</p><p>'+esc(x.vi||x.vietnamese||'')+'</p></div>').join('')+'</div>':'<div class="card">Server hiện chưa có <code>trilingual.json</code>. Chức năng đã sẵn sàng.</div>')}
function review(){$('view').innerHTML=shell('Ôn tập','Ôn lại toàn bộ kho từ bằng Flashcards.')+'<div class="card"><div class="big">'+db.vocab.length+'</div><p class="muted">Từ có thể ôn</p><button class="primary" onclick="show(\'flashcards\')">Bắt đầu ôn</button></div>'}
function stats(){const acc=db.stats.answered?Math.round(db.stats.correct/db.stats.answered*100):0;$('view').innerHTML=shell('Tiến độ','Theo dõi kết quả học tập.')+'<div class="grid"><div class="card"><div class="big">'+db.stats.xp+'</div><div class="muted">XP</div></div><div class="card"><div class="big">'+db.stats.learned+'</div><div class="muted">Từ đã học</div></div><div class="card"><div class="big">'+acc+'%</div><div class="muted">Độ chính xác</div></div></div>'}
function settings(){const au=db.profile.autoUpdate!==false?'selected':'';const off=db.profile.autoUpdate===false?'selected':'';$('view').innerHTML=shell('Cài đặt','Cập nhật nội dung tự động và giao diện.')+'<div class="card"><h2>☁️ Cập nhật GitHub</h2><p class="muted">Nguồn: <code>'+DATA_URL+'</code></p><p>Phiên bản nội dung đã nhận: <b>'+esc(db.lastRemoteVersion||'chưa có')+'</b></p><button class="primary" onclick="updateOnline(true)">🔄 Kiểm tra cập nhật ngay</button><label style="margin-top:18px">Tự động cập nhật khi mở app</label><select onchange="db.profile.autoUpdate=this.value===\'1\';save()"><option value="1" '+au+'>Bật</option><option value="0" '+off+'>Tắt</option></select></div><div class="card"><h2>Giao diện</h2><button onclick="db.profile.theme=db.profile.theme===\'dark\'?\'light\':\'dark\';save();render()">◐ Đổi Light/Dark</button></div>'}
$('theme').onclick=()=>{db.profile.theme=db.profile.theme==='dark'?'light':'dark';save();render()};load();render();setTimeout(()=>{if(db.profile.autoUpdate!==false)updateOnline(false)},700);
